version: '3.8'


services:
  showdown-worker:
    container_name: showdown-worker
    build:
      context: .
      dockerfile: docker/Worker
    ports:
      - "7071:7071"
    privileged: true
    restart: always
    volumes:
      - ./env/worker:/showdown/env
      - ./tmp/worker:/var/lib/showdown

  showdown-manager:
    container_name: showdown-manager
    build:
      context: .
      dockerfile: docker/Manager
    ports:
      - "7070:7070"
    privileged: true
    restart: always
    volumes:
      - ./env/manager:/showdown/env
      - ./tmp/manager:/var/lib/showdown
  
  showdown-dev:
    container_name: showdown-dev
    build:
      context: .
      dockerfile: docker/Dev
    ports:
      - "7070:7070"
    volumes:
      - .:/showdown
      - ./tmp/standalone:/var/lib/showdown
    privileged: true
    restart: always

  showdown-standalone:
    container_name: showdown-standalone
    build:
      context: .
      dockerfile: docker/Standalone
    ports:
      - "7070:7070"
    volumes:
      - ./env/standalone:/showdown/env
      - ./tmp/standalone:/var/lib/showdown
    privileged: true
    restart: always

  showdown-mq:
    container_name: showdown-mq
    build:
      context: .
      dockerfile: docker/Queue
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_USER
      - RABBIT_MQ_USER=$RABBIT_MQ_USER
      - RABBIT_MQ_PASSWORD=$RABBIT_MQ_PASSWORD
    restart: always
