version: '3.8'

services:
  showdown-server:
    container_name: showdown-server
    build:
      context: .
      dockerfile: docker/Server
    ports:
      - "8080:8080"
    privileged: true
    restart: always
    depends_on:
      - showdown-mq

  showdown-mq:
    container_name: showdown-mq
    build:
      context: .
      dockerfile: docker/Queue
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=$RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS=$RABBITMQ_DEFAULT_USER
      - RABBIT_MQ_USER=$RABBIT_MQ_USER
      - RABBIT_MQ_PASSWORD=$RABBIT_MQ_PASSWORD
    restart: always
