site_name: Showdown docs
plugins:
  - search
  - awesome-pages
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - pymdownx.snippets
extra_css:
  - stylesheets/extra.css
copyright: <a href='https://showdown.cambo.in'>Showdown is an open source remote code execution engine</a> built with &#10084; by <a href="https://cambo.in">Maninderpal Singh</a>
theme: 
  name: material
  logo: assets/images/favicon.png
  repo_url: https://github.com/msc24x/hunter
  repo_name: msc24x/showdown
  font:
    text: Poppins
  shortcuts:
    help: 191    # ?
    search: 83   # s
  user_color_mode_toggle: true
  features:
    - content.code.copy
    - content.tooltips
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference